import { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";
import AuthProvider from "@/context/oauth/AuthContext";
import ScreensaverOverlay from "../components/shared/ScreensaverOverlay";
import FlyoutMenu from "@/components/shared/FlyoutMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ header, children  }: { header: ReactNode, children: ReactNode }) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <AuthProvider value={false}>
          <header className="sticky top-0 z-50 p-2 bg-sky-600 text-white text-center text-sm">
            <div className="flex flex-row relative items-center justify-between w-full">
              <div className="absolute left-0">
                <FlyoutMenu>
                  {flyout}
                </FlyoutMenu>
              </div>
              <h1 id="main-header-title" className="text-4xl flex-1 text-center">
                {header}
              </h1>
            </div>
          </header>
          <main className="m-auto w-13/20 py-5">
            {children}
            <ScreensaverOverlay />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
